In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Data/kc_house_data.csv")
df.head()

,id,date,price,bedrooms,bathrooms,floors,waterfront,condition,grade,yr_built,yr_renovated,zipcode,lat,long
0,7129300520,20141013T000000,221900.0,3,1.00,1.0,0,3,7,1955,0,98178,47.5112,-122.257
1,6414100192,20141209T000000,538000.0,3,2.25,2.0,0,3,7,1951,1991,98125,47.7210,-122.319
2,5631500400,20150225T000000,180000.0,2,1.00,1.0,0,3,6,1933,0,98028,47.7379,-122.233
3,2487200875,20141209T000000,604000.0,4,3.00,1.0,0,5,7,1965,0,98136,47.5208,-122.393
4,1954400510,20150218T000000,510000.0,3,2.00,1.0,0,3,8,1987,0,98074,47.6168,-122.045

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            21613 non-null  int64
 1   date          21613 non-null  object
 2   price         21613 non-null  float64
 3   bedrooms      21613 non-null  int64
 4   bathrooms     21613 non-null  float64
 5   floors        21613 non-null  float64
 6   waterfront    21613 non-null  int64
 7   condition     21613 non-null  int64
 8   grade         21613 non-null  int64
 9   yr_built      21613 non-null  int64
 10  yr_renovated  21613 non-null  int64
 11  zipcode       21613 non-null  int64
 12  lat           21613 non-null  float64
 13  long          21613 non-null  float64
dtypes: float64(5), int64(8), object(1)
memory usage: 2.3+ MB

In [4]:
df.describe()

,id,price,bedrooms,bathrooms,floors,waterfront,condition,grade,yr_built,yr_renovated,zipcode,lat,long
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.401822e+05,3.370842,2.114757,1.494309,0.007542,3.409430,7.656873,1971.005136,84.402258,98077.939805,47.560053,-122.213896
std,2.876566e+09,3.673622e+05,0.930062,0.770163,0.539989,0.086517,0.650743,1.175459,29.373411,401.679240,53.505026,0.138564,0.140828
min,1.000102e+06,7.500000e+04,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1.000000,0.000000,3.000000,7.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1.500000,0.000000,3.000000,7.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2.000000,0.000000,4.000000,8.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,3.500000,1.000000,5.000000,13.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000

In [5]:
## in Korean
print('''
id: 집 고유아이디
date: 집이 팔린 날짜 
price: 집 가격 (타겟변수)
bedrooms: 주택 당 침실 개수
bathrooms: 주택 당 화장실 개수
floors: 전체 층 개수
waterfront: 해변이 보이는지 (0, 1)
condition: 집 청소상태 (1~5)
grade: King County grading system 으로 인한 평점 (1~13)
yr_built: 집이 지어진 년도
yr_renovated: 집이 리모델링 된 년도
zipcode: 우편번호
lat: 위도
long: 경도
''')

id: 집 고유아이디
date: 집이 팔린 날짜
price: 집 가격 (타겟변수)
bedrooms: 주택 당 침실 개수
bathrooms: 주택 당 화장실 개수
floors: 전체 층 개수
waterfront: 해변이 보이는지 (0, 1)
condition: 집 청소상태 (1~5)
grade: King County grading system 으로 인한 평점 (1~13)
yr_built: 집이 지어진 년도
yr_renovated: 집이 리모델링 된 년도
zipcode: 우편번호
lat: 위도
long: 경도

## Removing column less effective in analysis

In [6]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'floors', 'waterfront',
       'condition', 'grade', 'yr_built', 'yr_renovated', 'zipcode', 'lat',
       'long'],
      dtype='object')

In [7]:
columns_to_drop = ["id", "date", "zipcode", 'lat', 'long']

df= df.drop(columns= columns_to_drop)

# can done in same way like
#df = df.drop(columns_to_drop, axis = 1)

In [8]:
feature_coumns = df.columns.difference(["price"]) # x columns

x = df[feature_coumns]
y = df["price"]

In [9]:
# split the data in to training and test data 
x_train, x_test, y_train, y_test  = train_test_split(x,y,test_size = 0.3, random_state = 42 )
print(x_train.shape, x_test.shape, y_train.shape)

(15129, 8) (6484, 8) (15129,)

## Train model without bagging

In [10]:
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt
sm_train_x = sm.add_constant(x_train, has_constant="add") # Add Bias

sm_model = sm.OLS(y_train, sm_train_x) # create a model
fitted_sm_model = sm_model.fit() 
fitted_sm_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.595
Model:                            OLS   Adj. R-squared:                  0.595
Method:                 Least Squares   F-statistic:                     2776.
Date:                Fri, 23 Apr 2021   Prob (F-statistic):               0.00
Time:                        21:41:06   Log-Likelihood:            -2.0826e+05
No. Observations:               15129   AIC:                         4.165e+05
Df Residuals:                   15120   BIC:                         4.166e+05
Df Model:                           8
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         7.186e+06   1.73e+05     41.548      0.000    6.85e+06    7.52e+06
bathrooms     1.303e+05   3960.833     32.889      0.000    1.23e+05    1.38e+05
bedrooms     -2224.7910   2382.356     -0.934      0.350   -6894.497    2444.915
condition     1.641e+04   3169.013      5.178      0.000    1.02e+04    2.26e+04
floors        1946.3052   4336.838      0.449      0.654   -6554.422    1.04e+04
grade         1.956e+05   2199.540     88.924      0.000    1.91e+05       2e+05
waterfront    7.555e+05   2.26e+04     33.479      0.000    7.11e+05       8e+05
yr_built     -4300.7865     88.073    -48.832      0.000   -4473.420   -4128.153
yr_renovated    12.7325      5.043      2.525      0.012       2.847      22.618
==============================================================================
Omnibus:                    13447.374   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1684794.827
Skew:                           3.763   Prob(JB):                         0.00
Kurtosis:                      54.147   Cond. No.                     1.82e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.82e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Predict in test

In [11]:
sm_test_x = sm.add_constant(x_test, has_constant= "add") # Adding Bias in testing data
sm_model_predict  = fitted_sm_model.predict(sm_test_x) # Predict test data
print("RMSE: {}".format(sqrt(mean_squared_error(sm_model_predict, y_test)))) #RMSE
print(fitted_sm_model.params)

RMSE: 239804.29670858165
const           7.185671e+06
bathrooms       1.302689e+05
bedrooms       -2.224791e+03
condition       1.641020e+04
floors          1.946305e+03
grade           1.955909e+05
waterfront      7.555423e+05
yr_built       -4.300787e+03
yr_renovated    1.273246e+01
dtype: float64

## Check weather Bagging is better or not

In [12]:
import random
bagging_predict_result = [] # creating blank list

for _ in range(10):
    data_index = [data_index for data_index in range(x_train.shape[0])]
    # Training data index in list format
    
    random_data_index = np.random.choice(data_index, x_train.shape[0])
    # Random sampling of 1/10
    
    print(len(set(random_data_index)))
    sm_train_x = x_train.iloc[random_data_index,]
    sm_train_y = y_train.iloc[random_data_index,]
    sm_train_x = sm.add_constant(sm_train_x, has_constant="add")# add bias
    sm_model = sm.OLS(sm_train_y, sm_train_x) # Create a model
    fitted_sm_model = sm_model.fit() # 
    
    sm_test_x = sm.add_constant(x_test, has_constant="add") # add 
    sm_model_predict = fitted_sm_model.predict(sm_test_x) # Predict test data
    bagging_predict_result.append(sm_model_predict) 
    # in the case of lotto extracting method there will be around 63% data extraction
    pred = fitted_sm_model.predict(sm_test_x)
    print(sqrt(mean_squared_error(pred, y_test)))

9584
240210.6702707763
9607
239812.56251602538
9519
239701.20303576943
9485
240676.31958118413
9515
239854.31413693857
9571
239744.67859068786
9509
239934.89260603188
9592
239981.05422630924
9583
239600.83464201452
9555
240757.42644124478

In [13]:
 bagging_predict_result[0]

735      5.536575e+05
2830     7.164657e+05
4106     1.107659e+06
16218    1.469949e+06
19964    6.999366e+05
             ...
12606    5.961156e+05
14393    6.641392e+05
6899     3.217427e+05
85       8.759996e+05
21363    4.377838e+05
Length: 6484, dtype: float64

In [14]:
bagging_predict = [] 
for lst2_index in range(x_test.shape[0]):
    temp_predict = [] # 
    for lst_index in range(len(bagging_predict_result)):
        temp_predict.append(bagging_predict_result[lst_index].values[lst2_index])
    bagging_predict.append(np.mean(temp_predict))

In [15]:
bagging_predict

[563294.2761363046,
 711723.2432046345,
 1117499.996565299,
 1473640.1078080654,
 700205.3178224606,
 384625.7816177273,
 786617.6425961487,
 487454.35391231783,
 500568.6363261236,
 536045.5179054498,
 640657.6341871617,
 413108.5269150749,
 270308.9159766313,
 281444.11226852005,
 333758.8040437753,
 1261126.4757962772,
 317846.85235524795,
 1034464.9085927285,
 260487.14494801668,
 604636.9723673093,
 389727.70626547234,
 1300102.1609188097,
 820465.3780374953,
 581527.549574791,
 596821.7456300867,
 569256.484211904,
 268545.5503032721,
 41962.145334607456,
 563270.8490509975,
 639213.3696492659,
 564516.4595172717,
 458679.56190645753,
 556037.6562990913,
 684661.6494927233,
 410985.9260318788,
 876863.5052894093,
 935645.4832852628,
 639694.2383963338,
 391474.65638530505,
 1079471.267411271,
 452950.9229689751,
 151659.77071053852,
 488917.63195187534,
 223843.824191391,
 68908.8688069353,
 -42552.12224235451,
 248858.40284697377,
 286503.59632929665,
 363589.1290195578,
 714554.5501678282,
 327350.95538443263,
 244956.39930699096,
 929315.0145481793,
 268923.50757922913,
 462779.0547059608,
 1305526.949462254,
 593829.8358673891,
 773997.6883041204,
 308226.470181108,
 718226.6335726257,
 591156.376416745,
 333291.55201023613,
 194850.71378883842,
 615163.3273278165,
 432854.2390763268,
 168455.14031949974,
 379543.2287023255,
 1648383.5724347143,
 446660.2968707251,
 655243.9975390207,
 447634.44268477446,
 237944.12289991212,
 830817.6708237892,
 611890.9942563873,
 607609.8686283459,
 1229042.106028289,
 817172.2158288943,
 48497.11486299206,
 529960.533141806,
 1142693.0509787411,
 658216.8938000572,
 402564.814142091,
 708101.6629733827,
 360576.39011968777,
 901877.7257143103,
 624124.8149285761,
 639991.077258591,
 633550.5983840583,
 280218.16612731654,
 475149.11144090304,
 347142.6483397375,
 416410.714575323,
 671521.6119408973,
 1010919.655588245,
 335087.303425409,
 444010.2645053876,
 309329.63963426754,
 313523.2861402381,
 793485.5308653872,
 544063.4297984617,
 37081.49526237165,
 1058797.3213476345,
 1018034.843466435,
 464403.78726029367,
 1016808.8973252308,
 300926.75893351715,
 539034.8297200126,
 550978.1722383146,
 959851.7390913658,
 1705949.3721584626,
 596057.8556261526,
 128999.72699320325,
 682727.1766232647,
 756016.2151927886,
 665608.943118604,
 256326.98037250823,
 318908.2320448492,
 -119178.7558660252,
 224591.49953366173,
 333758.8040437753,
 385809.28717196314,
 205035.191351985,
 391498.0834706121,
 121058.34330717847,
 731507.9246281587,
 831555.5357942815,
 181068.08307974655,
 764894.9696362001,
 448350.6962054706,
 440113.81509235624,
 573557.274165016,
 426571.76505316264,
 403830.6029221282,
 780889.003658666,
 365100.6943657625,
 531186.4792830099,
 417900.6684717317,
 271540.05801410443,
 857672.5015903998,
 754790.269051585,
 645418.4637501698,
 950228.1081456814,
 821114.0620077105,
 435875.13005128235,
 127692.66243830006,
 399877.5370860553,
 574058.9720492564,
 5398.509855648316,
 458575.01640745066,
 447565.9770643644,
 681402.2391100058,
 780668.0873138388,
 672075.4470265787,
 922098.2373497995,
 827976.7543806795,
 771905.9046081107,
 731748.5052980565,
 701431.2639636642,
 726405.9999804137,
 483575.7774576422,
 764413.8999972693,
 360616.2327585212,
 286503.59632929665,
 263422.79651835514,
 252697.9432442366,
 338524.04719042964,
 135562.6243250983,
 297914.0200336474,
 546755.9027507674,
 468203.8432494048,
 725398.3722359024,
 357044.10464601836,
 528734.5870006024,
 624164.6575674092,
 447285.55375563307,
 506254.8346766381,
 389694.8751584197,
 705128.7667123463,
 283530.7000682601,
 109687.762241661,
 276339.5896726409,
 588704.4841343377,
 652587.6044653121,
 687427.7169097455,
 520217.28257875674,
 505993.4248695678,
 178789.82669962064,
 554612.4052628563,
 289601.2164031031,
 338721.5364499499,
 406787.08362963854,
 714027.7911703853,
 1129576.9529294241,
 1196060.4090336107,
 91089.1843205072,
 460466.35466512386,
 470108.99911246897,
 1073525.4748891983,
 555838.3514040599,
 449576.6423466743,
 252448.403917832,
 414880.9180400808,
 622915.2843408984,
 911441.0431146711,
 922062.1574712027,
 235653.03430887096,
 596821.7456300867,
 200638.20886681462,
 620222.8113885929,
 1136748.6915927012,
 309329.63963426754,
 444015.81863233924,
 543783.0064897308,
 309329.63963426754,
 354934.447991653,
 832274.588154975,
 779663.0575174624,
 356400.97480275447,
 425954.66024334077,
 330323.8516454692,
 1360939.2613113155,
 532188.5529005696,
 469769.71966324345,
 481788.9846989759,
 586655.4992559773,
 820607.1682272002,
 336889.7051561807,
 996130.1114060158,
 901597.3024055792,
 496369.7939238834,
 348345.1673956341,
 589953.8573608485,
 749804.1095601034,
 204353.38368198936,
 339925.8711413577,
 425070.5914994973,
 242428.58450715346,
 258196.05635697552,
 2063789.915478658,
 345145.80066281866,
 403089.5808809571,
 499342.6901849202,
 613336.6919303171,
 360033.41646058083,
 522788.794478529,
 345310.8170459685,
 602550.3845675692,
 559171.3562514943,
 733838.4976273514,
 800376.8462199329,
 612454.4388219849,
 410056.818752933,
 751475.4953931879,
 324437.56608729967,
 338721.5364499499,
 646601.9693044055,
 563231.0064121643,
 592662.7458666798,
 997641.3207115289,
 306356.7433732309,
 2470914.139542788,
 679211.105811259,
 898862.3888663057,
 1171762.0838987238,
 590830.9145729106,
 690301.263568045,
 980483.244568035,
 286928.4077758679,
 740406.949086198,
 478792.6613526322,
 484418.9945085613,
 207651.74178686057,
 172976.8466174393,
 479096.51174667047,
 446988.7148933758,
 1359251.2590328425,
 323453.3654280958,
 354871.17826751235,
 607911.9033868728,
 385769.4445331297,
 331528.1863368772,
 551400.385736751,
 257477.0039962818,
 474189.4784103112,
 451748.4039130785,
 420889.9802862945,
 314754.42817771167,
 630331.3664343099,
 333056.1672366079,
 287786.09325558785,
 790852.5648769856,
 491686.0274216107,
 126466.71629709649,
 347097.6098046348,
 714027.7911703853,
 684635.8943547029,
 506653.6210897675,
 550612.8677556475,
 472077.2238078111,
 621734.3767347977,
 514391.1096740483,
 590854.3416582178,
 266254.46171223104,
 670592.5046619511,
 354894.60535281943,
 859935.5362922108,
 546755.9027507674,
 447245.7111167998,
 303298.96593825816,
 317722.1285424784,
 381890.8680784541,
 136106.7627963067,
 972448.2662980867,
 1239878.1022915493,
 1006944.685709649,
 562905.5445683299,
 977433.4618693294,
 509690.9276182499,
 854300.4606855524,
 351318.0636566707,
 434368.7606013476,
 469786.13521676976,
 91089.1843205072,
 197823.61004987516,
 529314.8053504073,
 468203.8432494048,
 646379.3495211067,
 219922.8071497472,
 518649.4590401923,
 121058.34330717847,
 792299.4273630166,
 284829.6125480775,
 578880.1151575884,
 234374.5927355446,
 404094.6106773331,
 532432.0897492841,
 657699.1385929724,
 573158.4877518871,
 1026712.9515796468,
 56994.14927020995,
 1449027.2717444287,
 488617.8369108016,
 501452.70506996696,
 578059.9929590921,
 678565.3780198602,
 742193.7418448639,
 313203.0201926737,
 463059.4780146919,
 545289.3759396656,
 896443.3276909504,
 156155.45197503595,
 412148.6024489423,
 531427.059952908,
 556704.9955402862,
 292208.8081814721,
 1014396.8476816568,
 572977.4140458929,
 1047987.5868995797,
 961517.5707974993,
 683409.9482134993,
 310555.5857754712,
 913664.4726667221,
 413678.3989841842,
 609583.49011182,
 760175.2149561959,
 272539.5336835294,
 796253.9263351226,
 369779.2649717656,
 942279.8024163845,
 347114.0253581608,
 545669.1488511341,
 772538.8624128152,
 638609.4316214256,
 381594.02921619656,
 549870.5892015089,
 337490.3944124764,
 342298.07814609853,
 645119.0269397779,
 398405.8143786842,
 366806.368710729,
 323152.11298219237,
 703871.4728667166,
 654374.3972239782,
 391514.4990241385,
 468484.26655813586,
 526987.6368807694,
 280255.41081801464,
 553041.3329527476,
 431980.13804308046,
 465751.95096699754,
 613611.9193427785,
 405577.5530419609,
 382796.5482720931,
 372307.07977160264,
 1024926.1588209805,
 347114.0253581608,
 355516.90605891106,
 1193404.6216494597,
 757242.1613339924,
 351312.8677604011,
 447634.44268477446,
 557846.0605075534,
 704268.1250538097,
 515897.47912398336,
 401121.71441629675,
 411282.76489413646,
 468203.8432494048,
 440113.81509235624,
 468543.77352204,
 501794.58246732724,
 348625.5907043655,
 492816.67931304174,
 698174.1816336601,
 385473.41225229285,
 115072.70814627195,
 345888.07921695727,
 487972.1091194027,
 410841.53789403883,
 993731.6804973374,
 556379.5336964518,
 463744.24186350376,
 705253.7831178432,
 258618.06896354927,
 776371.7109443725,
 399791.22277608595,
 585755.0149586081,
 456267.5122628835,
 511290.4176308884,
 702495.4424932626,
 259263.79675494795,
 713122.1109767461,
 622898.8687873726,
 665850.6886006037,
 599936.1601640403,
 468345.6334391098,
 788826.6245844547,
 628323.6573308165,
 420569.71433873,
 419685.6455948867,
 319012.77754385554,
 748479.1720468441,
 354285.7640214379,
 385792.8716184368,
 78855.36364831887,
 436879.80161697714,
 445458.918358134,
 780889.003658666,
 1391469.4242542677,
 508200.97372184077,
 1015504.1482562324,
 527987.1125501943,
 64686.59931938797,
 561184.261251258,
 555153.587555248,
 496490.7549764165,
 782478.3071578119,
 433463.08040770853,
 965260.1120812837,
 318953.27057995193,
 147477.3438618239,
 564777.2185009324,
 730823.1607793468,
 1021007.7397274714,
 389968.2869353701,
 808472.4962658866,
 567750.114761969,
 314428.9663338774,
 548661.0586138314,
 914850.5761690926,
 416427.1301288491,
 573158.4877518871,
 348625.5907043655,
 552180.6912942114,
 1010518.271226981,
 422577.42344222387,
 482686.51281752915,
 441563.9263499317,
 516814.6715676072,
 277282.5145569781,
 560578.3760986921,
 318931.6591301562,
 320094.3355472196,
 309649.90558183205,
 251626.26346296174,
 494768.14931748307,
 632826.350127095,
 553503.0308593356,
 288009.96577923186,
 807713.8021582221,
 659604.1584189429,
 800377.5422661173,
 344124.7135435981,
 447285.55375563307,
 709828.9487681448,
 1994131.753781018,
 498864.7776166683,
 828582.6395332449,
 278471.2160074835,
 393306.48767907417,
 249461.69005140412,
 702957.2977386699,
 591156.376416745,
 197207.31182147347,
 648108.3387543404,
 315034.8514864428,
 689816.3394680126,
 967023.4777546428,
 1055459.1206039302,
 341128.3901972546,
 548321.7791646064,
 1064990.8017181535,
 468203.8432494048,
 868649.6930309206,
 729597.2146381428,
 539584.1640874903,
 921945.7866253821,
 782494.7227113381,
 28129.975372209494,
 333291.55201023613,
 193648.1947329417,
 476100.1884003271,
 524703.559821509,
 401105.2988627705,
 560561.9605451659,
 598026.0803214947,
 408338.49161467666,
 601921.072329697,
 288335.4276230658,
 800699.7101156323,
 321600.7049971543,
 430473.76859314536,
 368252.62550720247,
 1251542.6874894253,
 464285.4241558957,
 146395.7858584604,
 194857.72532061924,
 551919.9323105507,
 945748.8424347099,
 505413.2065197627,
 789590.5388571853,
 623544.5965787712,
 535043.4442878898,
 1048749.0798472413,
 159128.34823607252,
 1246988.127802838,
 726624.3183771062,
 635792.2348563506,
 847804.4604194403,
 512301.9239261736,
 108606.2042382976,
 953166.9167866986,
 328027.5671581581,
 751817.3727905484,
 1281648.6151433387,
 373521.8062555501,
 551954.2208224328,
 550954.7451530077,
 393910.1331141861,
 35318.12958901255,
 944562.7389323395,
 422676.77304496075,
 149368.68211949719,
 568976.0609031728,
 328857.32483436743,
 142196.94345622015,
 442829.71512996854,
 395673.4987875455,
 446059.6076144294,
 360920.0831525596,
 544667.0752335741,
 556659.9570051829,
 649334.2848955442,
 937631.5809389602,
 299100.1235360177,
 315431.03995143704,
 354285.7640214379,
 414880.9180400808,
 318403.93621247384,
 600260.4365198333,
 767712.2581021404,
 544376.339751075,
 848369.1365922801,
 836494.058802525,
 577373.7457076533,
 369498.84166303446,
 503020.5286085312,
 356697.8136650122,
 450930.56107219204,
 546231.1360119019,
 237418.99793036497,
 515857.6364851502,
 789590.5388571853,
 498841.3505313614,
 459865.66540882783,
 599188.7567385581,
 441283.5030412005,
 1077099.0604065307,
 1317788.2302911193,
 898474.7506784905,
 388782.1834329997,
 526987.6368807694,
 340265.1505905831,
 662194.8198574703,
 103524.75459515807,
 372290.66421807697,
 313066.9850217824,
 357907.34425268945,
 310230.12393163715,
 178078.77126518404,
 372076.10858162044,
 614837.8654839823,
 159997.9485511152,
 507134.4898368354,
 528256.6744323508,
 518040.6177088108,
 388711.49513012427,
 278105.9115248161,
 169681.08646070334,
 551376.9586514442,
 476601.5280538853,
 1252007.3415748305,
 539584.1640874903,
 2020703.3410971747,
 760597.4284546318,
 1008738.4900000959,
 662662.0718910096,
 458375.7115124192,
 525436.2288957315,
 1181776.11633018,
 777871.0688625266,
 568610.7564205053,
 557869.4875928607,
 874124.17816649,
 563979.0399851163,
 338716.3405536801,
 458055.4455648548,
 321926.1668409885,
 510192.26727180806,
 363332.1327961336,
 705409.1900210773,
 599228.5993773913,
 913664.4726667221,
 744025.5731386335,
 484129.61254332383,
 443571.63545342523,
 545957.7242349512,
 449418.63749530574,
 620828.6965411582,
 541325.9183110537,
 320117.7626325266,
 1060686.0616571724,
 353708.5018504492,
 617535.5343325572,
 179842.13693854297,
 1438074.684599503,
 821349.4467813384,
 684414.9780098756,
 486100.43518680055,
 696714.6663543392,
 586677.1107057736,
 310836.00908420247,
 556723.9161173387,
 525761.6907395656,
 1100869.1146644915,
 400778.02138342493,
 535513.2942695639,
 1128590.1543220852,
 484251.7384079581,
 434528.2228575462,
 558706.7021660897,
 1012610.0549229909,
 370503.8714594104,
 743419.6879860677,
 930459.8422756834,
 370503.8714594104,
 733796.0570403833,
 698214.0242724933,
 464041.08072576113,
 439168.2922598838,
 753490.3926515286,
 461091.6115500315,
 344124.7135435981,
 619925.972526336,
 179842.13693854297,
 340815.1357814708,
 464931.15194729454,
 584081.0311773887,
 490467.0928121877,
 769496.8111433529,
 404476.3307135269,
 270308.9159766313,
 269243.77352679346,
 501794.58246732724,
 863829.3877571074,
 807070.6723149584,
 306356.7433732309,
 161981.62487974408,
 396602.60606649175,
 57538.287741418,
 790491.0231545547,
 355511.71016264136,
 109367.49629409649,
 219322.11789345145,
 570162.1644055435,
 481149.8861894986,
 501794.58246732724,
 1005438.3162597138,
 1204169.317562411,
 956558.5768827647,
 472060.80825428467,
 689496.0735204481,
 357581.5241781737,
 553180.1669636362,
 264648.74265955866,
 408013.0297708422,
 248714.01470913374,
 797684.3732676274,
 462779.0547059608,
 288474.6198646363,
 395432.91811764764,
 258914.90782580673,
 527989.7104983295,
 500288.21301739255,
 455402.81525138265,
 550799.6964804555,
 80977.67309597433,
 691807.6330179799,
 517166.5166755648,
 529960.533141806,
 514391.1096740483,
 267336.0197155945,
 313528.4820365078,
 1232870.155290241,
 839995.6611857305,
 366525.94540199765,
 374702.7138616509,
 338159.17795300466,
 1033304.8301238001,
 649317.8693420182,
 419400.0263898857,
 160073.87106854498,
 405297.1297332299,
 157423.83870320758,
 836661.8740256722,
 85704.2384158968,
 325178.23598555365,
 272744.3927055125,
 522788.794478529,
 511418.21341301175,
 753787.2315137861,
 607666.1268207054,
 384045.92149860394,
 577008.441224986,
 667339.1850921833,
 450859.1392729655,
 482306.7399060606,
 754790.269051585,
 536654.3592368313,
 845097.585833475,
 382836.39091092657,
 311087.80941135704,
 517364.0059350849,
 667619.6084009146,
 430770.6074554029,
 586051.8538208653,
 937799.3247301653,
 631633.931139128,
 741769.1312901553,
 695505.135766662,
 809033.3428833489,
 163046.76732958172,
 483902.4912481353,
 443936.93993609294,
 826750.8082394756,
 830949.650641716,
 47709.79777375069,
 127692.66243830006,
 529459.1934882475,
 321897.5438594117,
 795991.3759847472,
 386995.39067433355,
 459806.15844492416,
 513241.0860502748,
 440080.9839853037,
 272744.3927055125,
 141515.13578622462,
 268386.7966600668,
 624725.5041848716,
 194874.14087414526,
 426274.92619090516,
 490424.00140181027,
 352522.3983480787,
 628323.6573308165,
 398389.3988251577,
 408013.0297708422,
 462779.0547059608,
 319270.93857938127,
 1214770.2024197942,
 714274.3142067294,
 330399.77416289924,
 442925.9076620266,
 883731.3935586478,
 760215.0575950289,
 83950.56935701091,
 489198.0552606063,
 404094.6106773331,
 212751.0684864701,
 814927.9814084672,
 530861.0174391756,
 604158.7015683759,
 514420.3402348794,
 813574.0626829498,
 681699.0779722633,
 949326.6640261874,
 655243.9975390207,
 878464.4525277537,
 418624.9167286952,
 961476.4716456986,
 674807.7626177173,
 790630.9977087484,
 501276.8272602426,
 587818.1756730408,
 433463.08040770853,
 462779.0547059608,
 333291.55201023613,
 950228.1081456814,
 604073.1695710304,
 435612.5797009069,
 92572.12668513507,
 179842.13693854297,
 299700.81279231346,
 930740.2655844146,
 718226.6335726257,
 559026.9681136542,
 393662.8335052357,
 501230.08528666786,
 381890.8680784541,
 705630.1063659047,
 172670.39827526585,
 688834.7367569434,
 613189.4233821119,
 373519.20830741496,
 149009.73834520095,
 446660.2968707251,
 487774.61985988246,
 386089.71048069437,
 716720.2641226907,
 320094.3355472196,
 386995.39067433355,
 643312.8624487692,
 306335.1319234351,
 634674.5969743903,
 733515.6337316519,
 747338.1070795769,
 631593.3924541103,
 422372.92265092226,
 771426.6911906641,
 521002.00171986315,
 718226.6335726257,
 1115530.4266621673,
 609235.4956923423,
 323814.90715052665,
 699924.8945137295,
 899516.5374749631,
 296407.6505837124,
 427781.2956408402,
 398365.97173985076,
 207470.66808086616,
 614517.5995364178,
 484718.78954963497,
 376505.9221738431,
 448791.9232055681,
 284492.93104698684,
 420866.55320098746,
 94101.92322037733,
 271540.05801410443,
 355516.90605891106,
 301816.0235736303,
 367467.70547423355,
 338099.23574385827,
 790895.0054639536,
 418174.08024868194,
 398709.6647727226,
 748804.6338906785,
 378878.129178584,
 85704.2384158968,
 419640.60705978377,
 297317.3861303162,
 656385.0625062883,
 299146.9777066318,
 510532.19754444325,
 825569.9006333749,
 601468.8265642055,
 624770.5427199749,
 574681.272755348,
 126483.13185062213,
 942536.7986398085,
 700205.3178224606,
 800376.8462199329,
 311736.49338157213,
 508966.32113060437,
 854880.6790353574,
 638204.2844999249,
 98300.76562261768,
 1040473.9708389423,
 272140.7472704005,
 722425.4759748657,
 568976.0609031728,
 768420.5863669158,
 629846.4423342773,
 567750.114761969,
 526987.6368807694,
 517038.5440912509,
 610644.2189780115,
 1266185.9598570531,
 493175.98131801945,
 815224.8202707247,
 569581.9460557384,
 334517.4981514396,
 148686.87444950175,
 476380.61170905817,
 637341.0448932536,
 454200.296195486,
 428647.93977706635,
 157423.83870320758,
 326125.00924322894,
 330321.25369733415,
 541793.1703445931,
 699522.5462322258,
 172653.9827217401,
 387018.8177596405,
 541350.4859396662,
 733796.0570403833,
 996095.1086227603,
 659442.839941261,
 335748.6401889133,
 872782.6677608856,
 827960.3388271534,
 917582.8917602312,
 267341.21561186423,
 1464077.12436959,
 293760.2161665098,
 422052.6567033579,
 603411.0262261056,
 254419.22656130893,
 293562.7269069898,
 603450.868864939,
 744303.7567299111,
 738632.9213178607,
 158847.92492734146,
 381594.02921619656,
 578554.6533137544,
 1568891.3443863317,
 666818.4737062817,
 521562.8483373254,
 867279.7169825584,
 640014.504343898,
 588487.3305497469,
 780309.1435395427,
 764238.022187545,
 567750.114761969,
 78388.11161477938,
 507580.91273320233,
 680496.5589163663,
 626659.2830295125,
 185266.9254819868,
 208552.2260842297,
 595333.6073691894,
 440139.84012579813,
 685921.3474598102,
 517083.58262635383,
 828257.1776894105,
 401098.28733098943,
 140305.60519854716,
 369317.7679570402,
 56894.799667472675,
 309329.63963426754,
 296407.6505837124,
 409776.3954442014,
 934459.3797828925,
 717105.2329304287,
 276964.8465575486,
 584220.0225270963,
 695219.1583309791,
 34108.599001334886,
 620508.4305935937,
 360925.2790488292,
 694780.5292790167,
 726869.3126306504,

In [16]:
print("RMSE: {}".format(sqrt(mean_squared_error(bagging_predict, y_test))))

RMSE: 239794.18134844195

### Using Function

In [17]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()
linear_model1 = regression_model.fit(x_train, y_train)
predict1 = linear_model1.predict(x_test)
print("RMSE : {}".format(sqrt(mean_squared_error(predict1, y_test))))

RMSE : 239804.29670858147

### Bagging with SK learn

In [18]:
from sklearn.ensemble import BaggingRegressor
bagging_model = BaggingRegressor(base_estimator=regression_model, # linear regression
                                n_estimators=5, # 5 times sampling
                                verbose=1) # show the process
linear_model2 = bagging_model.fit(x_train, y_train)
predict2 = linear_model2.predict(x_test)
print("RMSE: {}".format(sqrt(mean_squared_error(predict2, y_test)))) # Check RMSE

RMSE: 240004.77992690372

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

### lets do sampling more time

In [19]:
bagging_model2 = BaggingRegressor(base_estimator=regression_model,
                                 n_estimators=30,
                                 verbose = 1)

linear_model3 = bagging_model2.fit(x_train, y_train)
predict3 = linear_model3.predict(x_test)

print("RMSE: {}".format(sqrt(mean_squared_error(predict3, y_test))))

RMSE: 239828.98728959754

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

### Using Decision Tree

In [20]:
from sklearn.tree import DecisionTreeRegressor
decision_tree_model = DecisionTreeRegressor() # 

tree_model1 = decision_tree_model.fit(x_train, y_train)
predict1 = tree_model1.predict(x_test)
print("RMSE: {}".format(sqrt(mean_squared_error(predict1, y_test))))

# RMSE Result

RMSE: 297778.71577316936

In [28]:
x_train.head(2)

,bathrooms,bedrooms,condition,floors,grade,waterfront,yr_built,yr_renovated
167,2.50,4,3,2.0,9,0,1999,0
12412,1.75,4,5,1.0,7,0,1924,0

In [27]:
x_test.head(2)

,bathrooms,bedrooms,condition,floors,grade,waterfront,yr_built,yr_renovated
735,2.25,4,4,2.0,8,0,1986,0
2830,3.00,5,5,1.0,8,0,1977,0

In [29]:
x_train_sm.head()# run after below loop

,bathrooms,bedrooms,condition,floors,grade,waterfront,yr_built,yr_renovated
12312,1.75,3,3,1.0,7,0,1958,0
2056,1.00,2,4,1.0,6,0,1942,0
8869,2.00,4,4,2.0,8,0,1953,0
18201,2.00,3,3,2.0,8,0,1975,0
7507,1.50,3,3,1.0,7,0,1954,0

In [ ]:
## Same as upper for loop,
# change model to decision tree

In [30]:
import random
bagging_predict_result = [ ]
for _ in range(30):
    data_index = [data_index for data_index in range(x_train.shape[0])]
    random_data_index = np.random.choice(data_index, x_train.shape[0])
    
    print(len(set(random_data_index)))
    sm_train_x = x_train.iloc[random_data_index,]
    sm_train_y = y_train.iloc[random_data_index,]
    
    decision_tree_model = DecisionTreeRegressor()
    tree_model1 = decision_tree_model.fit(sm_train_x, sm_train_y)
    
    predict1 = tree_model1.predict(x_test)
    bagging_predict_result.append(predict1)

9547
9599
9542
9516
9618
9549
9602
9519
9488
9607
9557
9522
9568
9537
9587
9521
9581
9588
9574
9575
9582
9597
9585
9575
9582
9529
9600
9578
9601
9592

In [31]:
#  Same as upper, check array format  
bagging_predict = []
for lst2_index in range(x_test.shape[0]):
    temp_predict = []
    for lst_index in range(len(bagging_predict_result)):
        temp_predict.append(bagging_predict_result[lst_index][lst2_index])
    bagging_predict.append(np.mean(temp_predict)) #

In [32]:
print("RMSE: {}".format(sqrt(mean_squared_error(bagging_predict, y_test))))

RMSE: 233312.84845970199

In [36]:
bagging_predict_result[1].mean()

546667.063702063

### Comparing bagging result in Decision Tree Model

In [37]:
bagging_decision_tree_model1 = BaggingRegressor(base_estimator=decision_tree_model,
                                               n_estimators=5,
                                               verbose=1)


tree_model2 = bagging_decision_tree_model1.fit(x_train, y_train)
predict2 = tree_model2.predict(x_test)
print("RMSE: {}".format(sqrt(mean_squared_error(predict2, y_test))))

RMSE: 239437.052246656

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

In [38]:
bagging_decision_tree_model2 = BaggingRegressor(base_estimator=decision_tree_model,
                                             n_estimators=30,
                                               verbose=1)

tree_model3 = bagging_decision_tree_model2.fit(x_train, y_train)

predict3 = tree_model3.predict(x_test)

print("RMSE: {}".format(sqrt(mean_squared_error(predict3, y_test))))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

RMSE: 237070.74398462693

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

## Thank You